# Generated by Django 5.1.2 on 2024-11-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fligth',
            name='special_requests',
        ),
    ]
