# Generated by Django 5.1.2 on 2024-11-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_fligth_special_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fligth',
        ),
    ]
