# Generated by Django 5.1.2 on 2024-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_travel_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('destination', models.CharField(choices=[('Tsavo', 'Tsavo'), ('Malindi', 'malindi'), ('Serengeti', 'Serengeti'), ('Baringo', 'Baringo'), ('Diani', 'Diani')], max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
