# Generated by Django 5.1.2 on 2024-11-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_travel_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fligth',
        ),
        migrations.DeleteModel(
            name='travel',
        ),
    ]
