# Generated by Django 5.1.2 on 2024-11-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_fligth_alter_travel_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotel',
        ),
        migrations.DeleteModel(
            name='travel',
        ),
    ]
