# Generated by Django 5.1.2 on 2024-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_delete_hotel_delete_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('destination', models.CharField(choices=[('Maasai mara', 'Maasai mara'), ('Serena', 'serena'), ('Naivasha', 'Naivasha'), ('Rift hills', 'Rift hills'), ('Diani', 'Diani')], max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
