# Generated by Django 5.1.2 on 2025-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_explore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='title',
        ),
        migrations.RemoveField(
            model_name='explore',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='explore',
            name='country',
            field=models.CharField(default='Unknown Country', help_text='Country Name', max_length=100),
        ),
        migrations.AddField(
            model_name='explore',
            name='place_name',
            field=models.CharField(default='Unknown place', help_text='Name of the place', max_length=150),
        ),
        migrations.AddField(
            model_name='explore',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter price in USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='explore',
            name='image',
            field=models.ImageField(help_text='Upload an image', upload_to='destinations/'),
        ),
    ]
